In [1]:
import kNN

In [2]:
group, labels = kNN.createDataSet()

In [4]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [5]:
labels

['A', 'A', 'B', 'B']

In [7]:
group.shape

(4, 2)

In [8]:
from numpy import *

In [9]:
tile([4,5,6,7], 3)

array([4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7])

In [10]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [11]:
group.shape

(4, 2)

In [12]:
tile([4,5,6,7], 3).shape

(12,)

In [58]:
dataSetSize = group.shape[0]
diffMat = tile([2,0], (4,1)) - group

In [59]:
diffMat

array([[ 1. , -1.1],
       [ 1. , -1. ],
       [ 2. ,  0. ],
       [ 2. , -0.1]])

In [60]:
sqDiffMat = diffMat ** 2

In [61]:
sqDiffMat

array([[1.  , 1.21],
       [1.  , 1.  ],
       [4.  , 0.  ],
       [4.  , 0.01]])

In [62]:
sqDistances = sqDiffMat.sum(axis = 1)

In [63]:
sqDistances

array([2.21, 2.  , 4.  , 4.01])

In [64]:
distances = sqDistances ** 0.5

In [65]:
distances

array([1.48660687, 1.41421356, 2.        , 2.00249844])

In [66]:
sortedDistIndicies = argsort(distances)

In [67]:
sortedDistIndicies

array([1, 0, 2, 3])

In [68]:
distances[sortedDistIndicies]

array([1.41421356, 1.48660687, 2.        , 2.00249844])

In [69]:
classCount = {}
for i in range(4):
    voteILabel = labels[sortedDistIndicies[i]]
    classCount[voteILabel] = classCount.get(voteILabel, 0) + 1

In [70]:
classCount

{'A': 2, 'B': 2}

In [73]:
import operator
sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)

In [74]:
sortedClassCount

[('A', 2), ('B', 2)]

In [94]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat ** 2
    sqDistances = sqDiffMat.sum(axis = 1)
    distances = sqDistances ** 0.5
    sortedDistIndicies = argsort(distances)
    classCount = {}
    for i in range(k):
        voteILabel = labels[sortedDistIndicies[i]]
        classCount[voteILabel] = classCount.get(voteILabel, 0) + 1
    import operator
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]
    

In [104]:
dataSet = group
r = classify0([1,1],dataSet, labels, 3)

In [106]:
r

[('A', 2), ('B', 1)]

In [107]:
r[0][0]

'A'

In [2]:
import kNN

In [4]:
dataSet, labels = kNN.createDataSet()

In [5]:
r = classify0([1,1],dataSet, labels, 3)

In [6]:
r

'A'

In [7]:
dataSet

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [8]:
dataSet.min(0)

array([0., 0.])

In [14]:
dataSet.max(0)

array([1. , 1.1])