In [1]:
import numpy as np

In [7]:
a = np.zeros((5, 5))

In [16]:
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 9., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
z = np.ones((3,3))
z[1,1] = 9
a[1:-1, 1:-1] = z

In [15]:
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 9., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
A = np.diag((1,2,1,2,1))

In [32]:
A

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [33]:
A.T

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [68]:
B = np.random.randint(2, 10, size=(4,4))

In [69]:
B

array([[4, 9, 4, 5],
       [5, 3, 8, 9],
       [3, 3, 6, 2],
       [7, 6, 8, 8]])

In [55]:
B[:,0]

array([6, 8, 8, 3])

In [58]:
B[0:,1:3]

array([[9, 8],
       [5, 3],
       [3, 4],
       [7, 8]])

In [60]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [70]:
np.linalg.det(B)

467.9999999999998

In [71]:
np.linalg.det(np.eye(8))

1.0

In [79]:
np.diag((1,3,2,1))

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [80]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.eye(4) == np.diag((1,1,1,1))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
a = np.eye(4) == np.diag((1,1,1,1))

In [92]:
a.all()

True

In [93]:
z = np.ones((3,3))

In [94]:
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
y = np.random.randint(2,10,(6,6))

In [96]:
y

array([[9, 9, 3, 4, 9, 8],
       [3, 6, 2, 4, 8, 8],
       [5, 5, 9, 3, 9, 7],
       [7, 9, 6, 8, 2, 5],
       [6, 3, 2, 4, 5, 5],
       [5, 4, 7, 4, 3, 4]])

In [97]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'stand

In [117]:
np.random.rand(2,10,2)

array([[[0.5116113 , 0.08424323],
        [0.04909098, 0.39739883],
        [0.93600896, 0.55068893],
        [0.03707175, 0.44891663],
        [0.38689992, 0.23093883],
        [0.92285222, 0.29578859],
        [0.51873654, 0.5503398 ],
        [0.88368934, 0.62153575],
        [0.15268449, 0.46509946],
        [0.42108879, 0.10729682]],

       [[0.12254342, 0.21931368],
        [0.875392  , 0.79108293],
        [0.38254368, 0.60035835],
        [0.65625759, 0.55790054],
        [0.01712956, 0.7721602 ],
        [0.63043385, 0.11608815],
        [0.5056988 , 0.86049162],
        [0.16889714, 0.95535578],
        [0.08540253, 0.41723015],
        [0.54532371, 0.80402543]]])